name: harsh
description: A Flutter learning management system with live classes and admin panel.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core utilities
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.3
  
  # Google Sign-In
  google_sign_in: ^6.2.1
  
  # Video Player
  video_player: ^2.9.1
  chewie: ^1.8.3
  
  # PDF Viewer
  pdfx: ^2.6.0
  
  # Agora for Live Classes
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1
  
  # HTTP & Storage
  http: ^1.2.2
  path_provider: ^2.1.4
  
  # UI & Utils
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  
  # File picking & image handling
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  
  # Routing
  go_router: ^14.2.7
  
  # Dependency Injection
  get_it: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/placeholders/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
